name: python-project
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py36_0
  - intel-openmp=2019.4=233
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.2.0=py36hc64f4ea_0
  - mkl_random=1.1.1=py36h959d312_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.19.1=py36h3b9f5b6_0
  - numpy-base=1.19.1=py36hcfb5961_0
  - openssl=1.1.1h=haf1e3a3_0
  - pandas=1.1.2=py36hb1e8313_0
  - pip=20.2.3=py36_0
  - python=3.6.12=h26836e1_2
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - readline=8.0=h1de35cc_0
  - setuptools=50.3.0=py36h0dc7051_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/xueke/opt/anaconda3/envs/python-project
